server:
  port: 8090
  servlet:
    context-path: /springboot_1
spring:
  datasource: 
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: iloveyou.
    url: jdbc:mysql://localhost:3306/hotelsup
mybatis:
  mapper-locations: classpath*:mybatis/*Mapper.xml
  type-aliases-package: com.example.demo.model